# Problem 1

In [6]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a=np.random.randint(0,10,5)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.shape)

# 4 - matris'i yeniden boyutlandırın
a = a.reshape(5, 1)  
print(a)
# 5 - matris'in boyut sayısını öğrenin
print(a.ndim)


[1 0 7 2 9]
(5,)
[[1]
 [0]
 [7]
 [2]
 [9]]
2


# Problem 2

In [27]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
m=np.arange(0,10,3)
print(m)
# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([a,b,c]))


[0 3 6 9]
[0 3 6]
[9]
[]
[0 3 6 9]


# Problem 3

In [37]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
a=np.random.randint(5,100,2)

# 2 - matris'in özelliklerini inceleyin
a=np.random.randint(10,size=10)
print(a.ndim) #boyut sayısı
print(a.shape) #boyut bilgis
print(a.size) #toplam eleman sayısı
print(a.dtype) #veri tipi


1
(10,)
10
int32
