In [ ]:
#Numpy nedir?
#sayısal işlemleri hızlı yapamak için
#veri analizinde kullanılır
#kurmak için pip install numpy kullanılır
#bilimsel işlemlerde kullanılır.
#veri saklama ve vektör işlemleri için kullanılır

In [1]:
a=[1,2,3,4]
b=[2,3,4,5]
ab=[]
for i in range (0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


In [3]:
x=np.array([1,2,3,4,5,6,7,8,9])
multi=x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(multi.shape) #boyut için

(3, 3)


In [5]:
print(x.shape)

(9,)


In [6]:
print(x.ndim) #arraylerin boyut sayısı

1


In [7]:
print(multi.ndim)

2


In [11]:
#Birleştirme(Concatenation)
#Birleştirme yapmak için
x= np.array([1,2,3,4,5])
y= np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
z=np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [14]:
print(np.concatenate([a,a],axis=1))


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
#axis=0 ise satır bazında birleştirme yapar
#axis=1 ise sütun bazında birleştirme yapar


In [16]:
#array ayırma
m=np.array([1,2,3,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99,  3]), array([2, 1])]


In [17]:
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99  3]
[2 1]


In [19]:
#vsplit yatay ayırma
#hsplit dikey ayırma yapar
n= np.arange(16).reshape(4,4)
np.vsplit(n,[2]) #arange verdiğim aralıktakine göre alır. verdiğim sayı kadar atlıyor


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [20]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [21]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
#np.linspace(başlangıç,bitiş,bölünecek,aralık)
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
np.random.randint(0,10,3)

array([4, 1, 0], dtype=int32)

In [24]:
print(12)

12
