In [ ]:
#Numpy nedir?
#sayısal işlemleri hızlı yapamak için
#veri analizinde kullanılır
#kurmak için pip install numpy kullanılır
#bilimsel işlemlerde kullanılır.
#veri saklama ve vektör işlemleri için kullanılır

In [4]:
a=[1,2,3,4]
b=[2,3,4,5]
ab=[]
for i in range (0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [5]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


In [6]:
x=np.array([1,2,3,4,5,6,7,8,9])
multi=x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print(multi.shape) #boyut için

(3, 3)


In [8]:
print(x.shape)

(9,)


In [9]:
print(x.ndim) #arraylerin boyut sayısı

1


In [10]:
print(multi.ndim)

2


In [11]:
#Birleştirme(Concatenation)
#Birleştirme yapmak için
x= np.array([1,2,3,4,5])
y= np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [12]:
z=np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [13]:
a=np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [14]:
print(np.concatenate([a,a],axis=1))


[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [15]:
#axis=0 ise satır bazında birleştirme yapar
#axis=1 ise sütun bazında birleştirme yapar


In [16]:
#array ayırma
m=np.array([1,2,3,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99,  3]), array([2, 1])]


In [17]:
a,b,c=np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99  3]
[2 1]


In [18]:
#vsplit yatay ayırma
#hsplit dikey ayırma yapar
n= np.arange(16).reshape(4,4)
np.vsplit(n,[2]) #arange verdiğim aralıktakine göre alır. verdiğim sayı kadar atlıyor


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [19]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
#np.linspace(başlangıç,bitiş,bölünecek,aralık)
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [22]:
np.random.randint(0,10,3) #0 ile 10 arasında rastgele 3 sayı sıktı.

array([4, 4, 3], dtype=int32)

In [23]:
#arrange verilen sayı kadar atlar.
#linspace verilen aralık kadar değere böler.
np.random.randint(2,22,5)

array([12, 13, 15, 12, 17], dtype=int32)

In [26]:
npArray=np.arange(50)
npMulti=npArray.reshape(5,10)
print(npMulti.sum(axis=1))

[ 45 145 245 345 445]


In [28]:
a=np.random.randint(10,size=10)
print(a.ndim) #boyut sayısı
print(a.shape) #boyut bilgis
print(a.size) #toplam eleman sayısı
print(a.dtype) #veri tipi

1
(10,)
10
int32


In [32]:
#array sıralamak için sort() kullan.
v=np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [34]:
m=np.random.normal(20,5,(3,3)) #20 tane 20 den 5 e kadar oluştur ve adımlar 3 e 3 lük olsun
print(m)

[[13.22629913 21.74588009 19.88424167]
 [19.79717123 32.20110758 12.44792007]
 [23.36430045 20.21430769 26.10056889]]


In [35]:
print(np.sort(m,axis=0)) #yatayda sıralattık

[[13.22629913 20.21430769 12.44792007]
 [19.79717123 21.74588009 19.88424167]
 [23.36430045 32.20110758 26.10056889]]


In [36]:
print(np.sort(m,axis=1)) #dikeyde sıralattık

[[13.22629913 19.88424167 21.74588009]
 [12.44792007 19.79717123 32.20110758]
 [20.21430769 23.36430045 26.10056889]]


In [38]:
a=np.random.randint(10,size=10)
print(a[0])

8


In [39]:
print(a[-1])

5


In [40]:
a[0]=100
print(a)

[100   0   4   2   4   9   3   4   9   5]


In [41]:
x=np.random.randint(10,size=(3,5))
print(x)

[[8 1 3 1 9]
 [1 5 0 1 7]
 [6 7 5 0 8]]


In [44]:
print(x[0,0]) #0.elemanın 0.indexini getirriyoruz

8


In [43]:
print(x[1,1])

5


In [45]:
x[1,4]=100
print(x)

[[  8   1   3   1   9]
 [  1   5   0   1 100]
 [  6   7   5   0   8]]


In [47]:
x[1,4]=3.14
print(x)

[[8 1 3 1 9]
 [1 5 0 1 3]
 [6 7 5 0 8]]


In [49]:
a=np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [50]:
print(a[0:3])

[20 21 22]


In [51]:
print(a[:3])

[20 21 22]


In [52]:
print(a[3:]) #3 den sonsuza kadar git demek

[23 24 25 26 27 28 29]


In [53]:
print(a[1::2]) #1 den başla 2 şey atla

[21 23 25 27 29]


In [54]:
print(a[0::2])

[20 22 24 26 28]


In [55]:
print(a[2::2])

[22 24 26 28]


In [57]:
b=np.random.randint(10,size=[5,5])
print(b)

[[3 6 8 2 9]
 [6 4 6 1 9]
 [9 9 6 0 3]
 [3 7 4 9 2]
 [9 1 7 6 7]]


In [58]:
print(b[:,0]) #tüm satırlarda 0. sütunlardaki elemanları al demek

[3 6 9 3 9]


In [59]:
print(b[:,1])

[6 4 9 7 1]


In [61]:
print(b[0,:]) #0.sütundaki elemanları al

[3 6 8 2 9]


In [62]:
print(b[0:2,0:3]) #0-2 arasındaki satırları seç ve ilk 3 sütunundaki sayıları al

[[3 6 8]
 [6 4 6]]


In [63]:
print(b[::2,::2]) #2 şer 2 şer atlayarak git

[[3 8 9]
 [9 6 3]
 [9 7 7]]


In [65]:
alt_b=b[0:3,0:2]
alt_b

array([[3, 6],
       [6, 4],
       [9, 9]], dtype=int32)

In [69]:
alt_b=b[0,0]=100
alt_b=b[1,1]=200
alt_b #alt kümesini yazdırdık


200

In [70]:
print(b)

[[100   6   8   2   9]
 [  6 200   6   1   9]
 [  9   9   6   0   3]
 [  3   7   4   9   2]
 [  9   1   7   6   7]]


In [72]:
#Bir listeye arrayden istediğin indisi koyup listeden veri almak için : fancy index
v=np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [73]:
yetgen=[1,3,5] #1.3. ve 5. elemanları getirdi.
print(v[yetgen])

[ 3  9 15]


In [75]:
m=np.arange(9).reshape(3,3) #m=np.arange(9).reshape(3,3): Bu satır, 0'dan 8'e kadar olan sayılardan oluşan bir NumPy dizisi oluşturur ve bunu 3x3 boyutunda bir matris haline getirir.
satir=np.array([0,1]) #bu satır, iki elemanlı bir NumPy dizisi oluşturur. Bu dizinin elemanları matrisin hangi satırlarının seçileceğini belirtir.
sutun=np.array([1,2]) # Bu satır, iki elemanlı bir NumPy dizisi oluşturur. Bu dizinin elemanları matrisin hangi sütunlarının seçileceğini belirtir.
print(m[satir,sutun]) #Bu satır, belirtilen satır ve sütun indekslerinde kesişen elemanları seçer ve yazdırır.

[1 5]


In [76]:
v=np.array([1,2,3,4,5])
print(v>3)

[False False False  True  True]


In [77]:
print(v[v>3]) #true olanları getir dedik

[4 5]


In [78]:
print(v[v<3])

[1 2]


In [79]:
print(v[v>=3])

[3 4 5]


In [80]:
print(v[v<=3])

[1 2 3]


In [81]:
print(v[v!=3])

[1 2 4 5]


In [82]:
print(v[v==3])

[3]


In [83]:
print(v*2) #tüm elemanlarıyla 2 yi çarp

[ 2  4  6  8 10]


In [84]:
print(np.subtract(v,3)) #her birinden 3 çıkart

[-2 -1  0  1  2]


In [85]:
print(np.add(v,2)) #toplama

[3 4 5 6 7]


In [86]:
np.multiply(v,2)

array([ 2,  4,  6,  8, 10])

In [89]:
np.power(v,2) #üs alma

array([ 1,  4,  9, 16, 25])

In [88]:
np.mod(v,2) 

array([1, 0, 1, 0, 1])

In [92]:
#5*x0+x1=12
#x0+3*x1=10
a=np.array([[5,1],[1,3]])
b=np.array([12,10])
x=np.linalg.solve(a,b)
print(x) #a ve b yi çözmüş oldu.

[1.85714286 2.71428571]
